// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AccordionJs from "../../node_modules/react-bootstrap/esm/Accordion.js";
import * as AccordionToggleJs from "../../node_modules/react-bootstrap/esm/AccordionToggle.js";

var make = AccordionJs.default;

var make$1 = AccordionToggleJs.default;

var Toggle = {
  make: make$1
};

var make$2 = AccordionToggleJs.default;

var Collapse = {
  make: make$2
};

export {
  make ,
  Toggle ,
  Collapse ,
  
}
/* make Not a pure module */
