// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ButtonToggleGroupJs from "../../node_modules/react-bootstrap/esm/ButtonToggleGroup.js";

var make = ButtonToggleGroupJs.default;

export {
  make ,
  
}
/* make Not a pure module */
