// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ButtonJs from "../../node_modules/react-bootstrap/esm/Button.js";

var make = ButtonJs.default;

export {
  make ,
  
}
/* make Not a pure module */
