// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ButtonGroupJs from "../../node_modules/react-bootstrap/esm/ButtonGroup.js";

var make = ButtonGroupJs.default;

export {
  make ,
  
}
/* make Not a pure module */
