// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ButtonToolbarJs from "../../node_modules/react-bootstrap/esm/ButtonToolbar.js";

var make = ButtonToolbarJs.default;

export {
  make ,
  
}
/* make Not a pure module */
