// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CardJs from "../../node_modules/react-bootstrap/esm/Card.js";
import * as CardImgJs from "../../node_modules/react-bootstrap/esm/CardImg.js";

var make = CardJs.default;

function Card$Body(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "card-body"
            }, children);
}

var Body = {
  make: Card$Body
};

function Card$Header(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "card-header"
            }, children);
}

var Header = {
  make: Card$Header
};

function Card$Text(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "card-text"
            }, children);
}

var $$Text = {
  make: Card$Text
};

function Card$Title(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "card-title h5"
            }, children);
}

var Title = {
  make: Card$Title
};

var make$1 = CardImgJs.default;

var Img = {
  make: make$1
};

function Card$Subtitle(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "mb-2 text-muted"
            }, children);
}

var Subtitle = {
  make: Card$Subtitle
};

export {
  make ,
  Body ,
  Header ,
  $$Text ,
  Title ,
  Img ,
  Subtitle ,
  
}
/* make Not a pure module */
