// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as CarouselJs from "../../node_modules/react-bootstrap/esm/Carousel.js";
import * as CarouselItemJs from "../../node_modules/react-bootstrap/esm/CarouselItem.js";
import * as CarouselCaptionJs from "../../node_modules/react-bootstrap/esm/CarouselCaption.js";

var make = CarouselJs.default;

var make$1 = CarouselCaptionJs.default;

var Caption = {
  make: make$1
};

var make$2 = CarouselItemJs.default;

var Item = {
  make: make$2
};

export {
  make ,
  Caption ,
  Item ,
  
}
/* make Not a pure module */
