// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ColJs from "../../node_modules/react-bootstrap/esm/Col.js";

var make = ColJs.default;

export {
  make ,
  
}
/* make Not a pure module */
