// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ContainerJs from "../../node_modules/react-bootstrap/esm/Container.js";

var make = ContainerJs.default;

export {
  make ,
  
}
/* make Not a pure module */
