// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImageJs from "../../node_modules/react-bootstrap/esm/Image.js";

var make = ImageJs.default;

export {
  make ,
  
}
/* make Not a pure module */
