// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as JumbotronJs from "../../node_modules/react-bootstrap/esm/Jumbotron.js";

var make = JumbotronJs.default;

export {
  make ,
  
}
/* make Not a pure module */
