// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ListGroupJs from "../../node_modules/react-bootstrap/esm/ListGroup.js";
import * as ListGroupItemJs from "../../node_modules/react-bootstrap/esm/ListGroupItem.js";

var make = ListGroupJs.default;

var make$1 = ListGroupItemJs.default;

var Item = {
  make: make$1
};

export {
  make ,
  Item ,
  
}
/* make Not a pure module */
