// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as NavJs from "../../node_modules/react-bootstrap/esm/Nav.js";
import * as NavLinkJs from "../../node_modules/react-bootstrap/esm/NavLink.js";

var make = NavJs.default;

var make$1 = NavLinkJs.default;

var Link = {
  make: make$1
};

var make$2 = NavLinkJs.default;

var Item = {
  make: make$2
};

export {
  make ,
  Link ,
  Item ,
  
}
/* make Not a pure module */
