// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as NavbarJs from "../../node_modules/react-bootstrap/esm/Navbar.js";
import * as NavbarBrandJs from "../../node_modules/react-bootstrap/esm/NavbarBrand.js";
import * as NavbarToggleJs from "../../node_modules/react-bootstrap/esm/NavbarToggle.js";
import * as NavbarCollapseJs from "../../node_modules/react-bootstrap/esm/NavbarCollapse.js";

var make = NavbarJs.default;

var make$1 = NavbarBrandJs.default;

var Brand = {
  make: make$1
};

var make$2 = NavbarCollapseJs.default;

var Collapse = {
  make: make$2
};

var make$3 = NavbarToggleJs.default;

var Toggle = {
  make: make$3
};

export {
  make ,
  Brand ,
  Collapse ,
  Toggle ,
  
}
/* make Not a pure module */
