// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as NavDropdownJs from "../../node_modules/react-bootstrap/esm/NavDropdown.js";
import * as DropdownItemJs from "../../node_modules/react-bootstrap/esm/DropdownItem.js";

var make = NavDropdownJs.default;

var make$1 = DropdownItemJs.default;

var Item = {
  make: make$1
};

export {
  make ,
  Item ,
  
}
/* make Not a pure module */
