// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as RowJs from "../../node_modules/react-bootstrap/esm/Row.js";

var make = RowJs.default;

export {
  make ,
  
}
/* make Not a pure module */
