// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as SafeAnchorJs from "../../node_modules/react-bootstrap/esm/SafeAnchor.js";

var make = SafeAnchorJs.default;

export {
  make ,
  
}
/* make Not a pure module */
