// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as NavJs from "../../node_modules/react-bootstrap/esm/Nav.js";

var make = NavJs.default;

export {
  make ,
  
}
/* make Not a pure module */
