// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as TabsJs from "../../node_modules/react-bootstrap/esm/Tabs.js";

var make = TabsJs.default;

export {
  make ,
  
}
/* make Not a pure module */
