// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ToggleButtonJs from "../../node_modules/react-bootstrap/esm/ToggleButton.js";

var make = ToggleButtonJs.default;

export {
  make ,
  
}
/* make Not a pure module */
